import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import mysql from 'mysql2'
import Link from 'next/link'

const Home: NextPage = () => {

  const conn = mysql.createConnection({
    host     : process.env.DB_HOST,
    user     : process.env.DB_USER,
    password : process.env.DB_PASS,
    database : process.env.DB_NAME,
    charset : 'cp1251'
  })
  const sql = 'SELECT * FROM t2 AS solution';
  // const sql = 'INSERT INTO t2 (c) VALUES ("Царевна-лягушка")';

  conn.promise().query(sql)
  .then( ([rows,fields]) => {
    console.log("Rows: ", rows);
  })
  .catch(console.log)
  .then( () => conn.end(function(err) {console.log(err);}));

  return (
    <div className={styles.container}>
      <Head>
        <title>Connect DB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Connect DB
        </h1>
      </main>

      <footer className={styles.footer}>
        <Link href="/">Back to the Future</Link>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
      </footer>
    </div>
  )
}

export default Home
