import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

export interface User {
  id: number,
  name:string
}

const Home: NextPage = () => {
const [users, setUsers]  = useState<string[]>([]);
useEffect(()=>{
  fetch('/api/users').then((res)=>res.json()).then((res:{data:User[]})=>{
    console.log("res=", res);
    setUsers(res.data.map(el=>el.name));
  })
},[]
)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Go to <Link href="/db"><a>DB Connect!</a></Link>
        </h1>
{users.map(user=><div>{user}</div>)}
        <div className={styles.grid}>
          <a href="/db" className={styles.card}>
            <h2>DB Connect &rarr;</h2>
            <p>Select * from t2</p>
          </a>

          <Link href="/bar"><a className={styles.card}>
            <h2>BAR &rarr;</h2>
            <p>/bar/index.tsx</p>
          </a></Link>

          <Link href="/bar/foo"><a className={styles.card}>
            <h2>BAR/foo &rarr;</h2>
            <p>/bar/foo.tsx</p>
          </a></Link>

          <Link href="/db"><a className={styles.card}>
            <h2>DB &rarr;</h2>
            <p>/db</p>
          </a></Link>
        </div>
      </main>

      <footer className={styles.footer}>        <Link href="/">Back to the Future</Link>

          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
      </footer>
    </div>
  )
}

export default Home
